<a href="https://colab.research.google.com/github/laresamdeola/Natural-Language-Processing/blob/main/NLP_Malware_Result_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import nltk

In [2]:
data = pd.read_csv('malicious_phish.csv')

In [3]:

import re
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

sites = []

for i in range(0, len(data[:10000])):
  links = re.sub('[^a-zA-Z]', ' ', data['url'][i])
  links = links.lower()
  links = links.split()
  ps = PorterStemmer()
  links = [ps.stem(word) for word in links if not word in set(stopwords.words('english'))]
  links = ' '.join(links)
  sites.append(links)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [4]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(sites).toarray()
y = data.iloc[:10000, -1].values

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [6]:
from sklearn.naive_bayes import GaussianNB
nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)

GaussianNB()

In [7]:
y_pred = nb_classifier.predict(X_test)

In [8]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
acc = accuracy_score(y_test, y_pred)

In [9]:
print(cm)

[[1231    5  182   44]
 [  40  295   17   12]
 [   8    3   36    2]
 [  16    1   45   63]]


In [10]:
print(acc)

0.8125
