<a href="https://colab.research.google.com/github/laresamdeola/Natural-Language-Processing/blob/main/NLP_Malware_Research_Results%20II.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import nltk

In [2]:
data = pd.read_csv('malicious_phish.csv')

In [3]:
type(data)

pandas.core.frame.DataFrame

In [4]:
len(data)

651191

In [5]:
import re
#nltk.download('stopwords')
#from nltk.corpus import stopwords
#from nltk.stem.porter import PorterStemmer

sites = []

for i in range(0, len(data[:25000])):
  links = re.sub('[^a-zA-Z]', ' ', data['url'][i])
  links = links.lower()
  links = links.split()
  #ps = PorterStemmer()
  #links = [ps.stem(word) for word in links if not word in set(stopwords.words('english'))]
  links = ' '.join(links)
  sites.append(links)

In [6]:
print(sites[:100])

['br icloud com br', 'mp raid com music krizz kaliko html', 'bopsecrets org rexroth cr htm', 'http www garage pirenne be index php option com content view article id vsig', 'http adventure nicaragua net index php option com mailto tmpl component link ahr cdovl fkdmvudhvyzs uawnhcmfndweubmv l luzgv lnbocd vchrpb y tx nvbnrlbnqmdmlldz hcnrpy xljmlkptq omfib v jmnhdglkptm omrlbw tyxj awnszxmmsxrlbwlkptu', 'http buzzfil net m show art ils etaient loin de s imaginer que le hibou allait faire ceci quand ils filmaient html', 'espn go com nba player id brandon rush', 'yourbittorrent com q anthony hamilton soulife', 'http www pashminaonline com pure pashminas', 'allmusic com album crazy from the heat r', 'corporationwiki com ohio columbus frank s benson p aspx', 'http www ikenmijnkunst nl index php exposities exposities', 'myspace com video vid', 'http www lebensmittel ueberwachung de index php aktuelles', 'http www szabadmunkaero hu cimoldal html start', 'http larcadelcarnevale com catalogo pa

In [7]:
sites_half = sites[:32500]

In [8]:
len(sites)

25000

In [9]:
print(data.type)

0           phishing
1             benign
2             benign
3         defacement
4         defacement
             ...    
651186      phishing
651187      phishing
651188      phishing
651189      phishing
651190      phishing
Name: type, Length: 651191, dtype: object


In [10]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(sites).toarray()
y = data.iloc[:25000, -1].values

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [12]:
from sklearn.naive_bayes import GaussianNB
nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)

GaussianNB()

In [13]:
from sklearn.tree import DecisionTreeClassifier
dt_classifier = DecisionTreeClassifier()
dt_classifier.fit(X_train, y_train)

DecisionTreeClassifier()

In [14]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier = GaussianNB()
rf_classifier.fit(X_train, y_train)

GaussianNB()

In [15]:
y_pred = nb_classifier.predict(X_test)
y_pred_dt = dt_classifier.predict(X_test)
y_pred_rf = rf_classifier.predict(X_test)

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
acc = accuracy_score(y_test, y_pred)

cm_dt = confusion_matrix(y_test, y_pred_dt)
acc_dt = accuracy_score(y_test, y_pred_dt)

cm_rf = confusion_matrix(y_test, y_pred_rf)
acc_rf = accuracy_score(y_test, y_pred_rf)

In [17]:
print(cm)
print(cm_dt)
print(cm_rf)

[[3188    6  457   57]
 [  39  816   30   10]
 [  22    6   81    2]
 [  45    8  108  125]]
[[3662   13    2   31]
 [  14  876    2    3]
 [  14    6   84    7]
 [ 127   27    3  129]]
[[3188    6  457   57]
 [  39  816   30   10]
 [  22    6   81    2]
 [  45    8  108  125]]


In [18]:
print(acc)
print(acc_dt)
print(acc_rf)

0.842
0.9502
0.842
