In [84]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import nltk

In [85]:
corpus = pd.read_csv('df_selected_efe.csv')

In [86]:
corpus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 3 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Preprocessed_Comment  1973 non-null   object 
 1   VADER_Sentiment       2000 non-null   float64
 2   SentimentalLabel      1999 non-null   object 
dtypes: float64(1), object(2)
memory usage: 47.0+ KB


In [87]:
corpus = corpus.dropna()

In [88]:
len(corpus)

1973

In [89]:
#features = corpus.iloc[:, 0:2].values
comments = corpus.iloc[:, 0].values
sentiments = corpus.iloc[:, -1].values

In [90]:
len(comments)

1973

In [91]:
len(sentiments)

1973

In [93]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
comments = cv.fit_transform(comments)

In [94]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
sentiments = le.fit_transform(sentiments)

In [95]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(comments, sentiments, test_size=0.2, random_state=0)

In [100]:
X_train = X_train.toarray()
X_test = X_test.toarray()

In [102]:
from sklearn.naive_bayes import GaussianNB
nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)

GaussianNB()

In [103]:
y_pred = nb_classifier.predict(X_test)

In [104]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm = confusion_matrix(y_test, y_pred)
acc = accuracy_score(y_test, y_pred)

In [105]:
print(cm)

[[ 15  33   5]
 [ 74 159  48]
 [ 10  39  12]]


In [106]:
print(acc)

0.4708860759493671


In [107]:
from sklearn.tree import DecisionTreeClassifier
dt_classifier = DecisionTreeClassifier()
dt_classifier.fit(X_train, y_train)

DecisionTreeClassifier()

In [108]:
y_pred_dt = dt_classifier.predict(X_test)

In [109]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cm_dt = confusion_matrix(y_test, y_pred_dt)
acc_dt = accuracy_score(y_test, y_pred_dt)

In [110]:
print(cm_dt)
print(acc_dt)

[[  5  36  12]
 [ 16 233  32]
 [  2  46  13]]
0.6354430379746835


In [111]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier()
rf_classifier.fit(X_train, y_train)

RandomForestClassifier()

In [112]:
y_pred_rf = rf_classifier.predict(X_test)

In [113]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cm_rf = confusion_matrix(y_test, y_pred_rf)
acc_rf = accuracy_score(y_test, y_pred_rf)

In [114]:
print(cm_rf)
print(acc_rf)

[[  1  50   2]
 [  2 268  11]
 [  1  55   5]]
0.6936708860759494


In [116]:
from xgboost import XGBClassifier
xg_classifier = XGBClassifier()
xg_classifier.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, objective='multi:softprob', ...)

In [117]:
y_pred_xg = xg_classifier.predict(X_test)

In [118]:
from sklearn.metrics import confusion_matrix, accuracy_score
xg_cm = confusion_matrix(y_test, y_pred_xg)
xg_acc = accuracy_score(y_test, y_pred_xg)

In [119]:
print(xg_cm)
print(xg_acc)

[[  5  42   6]
 [  7 256  18]
 [  1  47  13]]
0.6936708860759494


In [ ]:
# To do
# Adaboost
# Stacking Ensemble
# Artificial Neural Networks (ANN)